version: "3.9"
services:
  fts-server:
    container_name: fts-server
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./fts-server:/fts-server
    environment:
      FLASK_ENV: development
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - backend

  mongodb:
    container_name: dis_mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27018:27017
    expose:
      - 27017
    volumes:
      - ./.mongodb:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge